### ISSUE TITLE
Issue with Building cov-gtk on ubuntu14.04

### ISSUE THREAD

**Issue by techiudr** [inorton/XR.Baboon#15]
Hi,
I am trying to use package on ubunut 14.04. I have below setup for building package but it is resulting in below error while building.
error CS0246: The type or namespace name `TreeModel' could not be found

Package version on my Ubuntu14.04 :
Mono : 4.0.0.
Gtk-Sharp : Gtk built from below master
https://github.com/mono/gtk-sharp

Could you please let me know what is compatible version for building & running.

**Comment by inorton** [comment]
Hi there,

I've been using debian and ubuntu, but both a bit newer than 14.04.  You should be able to install `libgtk2.0-cil-dev` and `libgtk2.0-cil`

**Comment by techiudr** [comment]
Thanks for quick response.
I tried adding above package on ubuntu 14.04  but still getting same error.

Now i am moving my self to Latest Ubuntu 18.04 for checking. Please let me know other than installing above package anything else need's to be done.
Thanks

**Comment by pracplayopen** [comment]
using ubuntu 18.3, was not able to get either bash make_bundle.sh or make to build.  In former case it appears that there maybe some ios-specific mono settings assumed, but even when supplied correct mkbundle params there might be some variable addressing issues.

what did work (and far easier): 

```
git clone <XR.Baboon-git-url>
cd XR.Baboon
msbuild /p:Configuration=Release *.sln
```

This worked perfectly (as did 'make install').

monodevelop build of sln should likely work also, assuming prereqs author mentioned are installed.

**Comment by inorton** [comment]
Hi, yes, I think mkbundle for non-apple has gradually bitrotted since I first wrote baboon.
