### ISSUE TITLE
xml/json or text-based report?

### ISSUE THREAD

**Issue by pracplayopen** [inorton/XR.Baboon#24]
thanks for share

your tool is interesting and it worked better and easier than built-in coverage profiler.

any possibility of having an xml/json, or text-based output, vs just xml or gui?

w/rawer output like this, easier to summarize across multiple apps and projects.

also makes easier for others to use since they can customize their own stylesheet or javascript w/out touching your project.

just a request though, thanks

**Comment by inorton** [comment]
Hi, thanks for the request :)

Can you explain a bit more? What kind of new output do you imagine? Can you give a short example?

Thanks

**Comment by pracplayopen** [comment]
html/xml/json are similar (txt not too diff, if understand html/xml).

difference is that html is targetted at humans.

xml/json targetted at tools (which humans use after N-number-of-hops)

basic idea, instead of outputting a table in html, output a "coverage-metric" in xml or json

so instead of an html table like:

<tr>
<td>SomeMethod
<td name="calls">5</td>
  <td name="lines">10</td> 
<td name="hits">50</td> 
<td name="coverage">70</td>   
</tr>

output a non-visual, data-only direct representation of same: (eg, XML):

<coverage-metric name="SomeMethod">
<calls>5</calls>
<lines>10</lines>
<hits>50</hits>
<coverage-pct>70</coverage-pct>
</coverage-metric>

not as good at json so maybe wrong, but json simpler/cheaper so eg:
{
{ 
 "coverage-name": "SomeMethod1",
 "calls": "5",
 "lines": "10",
 "hits" : "50",
 "coverage-pct": "70"
},
{ 
 "coverage-name": "SomeMethod2",
 "calls": "20",
 "lines": "20",
 "hits" : "3",
 "coverage-pct": "100"
}

}

your code seems pretty designed to this, but you have more experience.

if not make sense, please say what is missing

**Comment by inorton** [comment]
The tool will save code coverage data to a sqlite database.  You could consume this data directly and render a json/xml report from that?

**Comment by inorton** [comment]
It might be a good idea to adopt a more conventional output format for coverage that could be understood by other tools? perhaps Cobertura?

**Comment by pracplayopen** [comment]
that's interesting re: sqllite backend.   i don't think it improves the ease of this task though, adapting your existing html-output tool would skip over needing to write seperate sqllite reading code.

adapting the html output to output json/xml should be pretty trivial... once you've read from the db into a code record, you'd just call the one-liner/one-method serializer for (xml/json/whatever) and print that.

I suppose you could try to match other projects, but that seems to be making it more complicated?   Also if you wanted to match something, probably better to match .net coverage tool like coverlet.  Also again once you're in a platform-neutral, display-neutral format like json/xml the advantage is people can adapt it however they need.

**Comment by pracplayopen** [comment]
Not sure if this would compile as is, but you can see it should be quite simple.


```
using Newtonsoft.Json;

//[...]

 public static void Main (string[] args)
        {
            // expect first arg to be a cov db
            if ( args.Length == 2 && File.Exists( args[0] ) ){
                try {

                    var index = new ReportIndex();
                    index.ProjectName = args[1];
                    index.LoadCoverage( args[0] );


                    if (!Directory.Exists("html"))
                        Directory.CreateDirectory("html");

                    File.WriteAllText( Path.Combine("html","cov.json"), JsonConvert.SerializeObject(index.Records, Formatting.Indented) );

                } catch ( Exception ex ) {
                    Console.Error.Write( ex.Message );

                }
            } else {
                Usage();
            }
        }
```

**Comment by pracplayopen** [comment]
[here is a .net resource on xml coverage outputs w/reportgenerator](https://medium.com/bluekiri/code-coverage-in-vsts-with-xunit-coverlet-and-reportgenerator-be2a64cd9c2f)

perhaps you saw this already cause it does mention cobertuna even for .net tools.   However this seems to be quite a few steps and for slightly different purposes than simply outputting in modern text formats, fwiw.

**Comment by pracplayopen** [comment]
closing as these have been merged into main
