### ISSUE TITLE
Sample code coverage?

### ISSUE THREAD

**Issue by scoutmedia-brian** [inorton/XR.Baboon#7]
Is there way to sample the code coverage?  If I code coverage the entire namespace I notice that it slows down all the calls.  I realize I can limit them to specified classes using the covcfg file but is that the only solution?

**Comment by inorton** [comment]
Hi Brian, Thank-you for trying out baboon :) 

The coverage system uses the debugger interface, it works by basically putting a break point at every branch in the program/class and recording when they are hit.

I'd not thought about sampling, it sounds a good idea.  I am not sure how responsive the debugger is to enabling/disabling breakpoints so it might even make things slower. It is worth exploring though.

**Comment by inorton** [comment]
@scoutmedia-brian a commit https://github.com/inorton/XR.Baboon/commit/5760408131a17ad0f4a731604d83fefd865cf693 by @mpdeimos should fix your issue
